build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.15
  amd64: ghcr.io/home-assistant/amd64-base:3.15
  armhf: ghcr.io/home-assistant/armhf-base:3.15
  armv7: ghcr.io/home-assistant/armv7-base:3.15
  i386: ghcr.io/home-assistant/i386-base:3.15
codenotary:
  base_images:
    - ghcr.io/home-assistant/aarch64-base:3.15
    - ghcr.io/home-assistant/amd64-base:3.15
    - ghcr.io/home-assistant/armhf-base:3.15
    - ghcr.io/home-assistant/armv7-base:3.15
    - ghcr.io/home-assistant/i386-base:3.15
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: AI Automation Builder"
  org.opencontainers.image.description: "Create Home Assistant automations using natural language with a local LLM"
  org.opencontainers.image.source: "https://github.com/yourusername/ai-automation-builder"
  org.opencontainers.image.licenses: "Apache-2.0"
  org.opencontainers.image.documentation: "https://github.com/yourusername/ai-automation-builder/blob/main/README.md" 